# -*- coding: utf-8 -*-
"""PalmerPenguinsM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQSs8D1-pFsnF0JpyLWliXvyvIGmsGP9
"""

# PalmerPenguinsM3.py
# Joshua Voisard
# 10/05/2026
# User lists and formatted output to analyze Palmer Penguin statistics

#Math import for function
import math

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151



# Variable declaration
largest_count = max(species_counts)
smallest_count = min(species_counts)
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]
total_penguins = sum(species_counts)
average_penguins = total_penguins / total_species
chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100
average_penguins_rounded_up = math.ceil(average_penguins)


# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least. . .")
print("\t" + SP_ADELIE + "!")
print()
print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")

# Dictate the total number of penguins alongside the average penguins per species
print(f"There are a total of {total_penguins} penguins in the dataset")
print(f"The average number of penguins per species is " +
      f"({average_penguins:.1f}.")
print("The average rounded up is " +
      str(average_penguins_rounded_up) +
      " penguins.")
print()

# Dictate the species counts alongside other counts
print(f"{species_names[0]}:{species_counts[0]}"
      f"({chinstrap_percent:.2f}%)")
print(f"{species_names[1]}:{species_counts[1]}"
      f"({gentoo_percent:.2f}%)")
print(f"{species_names[2]}:{species_counts[2]}"
      f"({adelie_percent:.2f}%)")
print()
print("The species with the most observations is Adelie with " +
      str(largest_count) + " penguins.")
print("The species with the least observations is Chinstrap with " +
      str(smallest_count) + " penguins.")